# Generated by Django 5.1.4 on 2025-01-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crudappmodel',
            old_name='todos',
            new_name='crudapps',
        ),
    ]
